// Generated by Wrangler
// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface CloudflareEnv {
  ASSETS: Fetcher;
  IMAGES: any; // Image optimization binding
  // NEXT_INC_CACHE_R2_BUCKET: R2Bucket; // Uncomment when using R2 for caching
  WORKER_SELF_REFERENCE: Fetcher;
}